### ISSUE TITLE
Membrane.Source implementation

### ISSUE THREAD

**Issue by dmorn** [membraneframework/membrane_http_adaptive_stream_plugin#46]
In our usecase we need an HLS stream to be injested by an RTC engine, as people in the room will be commenting on the stream. In our understanding, the first step would be to create a Source implementation that is capable of providing HLS chunks.

Do you have any feedback? Should we fork this plugin and add the source implementation in there?

**Comment by mat-hek** [comment]
Hi there, would you like to deliver the stream via HLS or WebRTC? If you already have HLS, I'd consider delivering that HLS directly to users and using RTC Engine only for communication between these users.

**Comment by dmorn** [comment]
Hey @mat-hek thanks for joining! I'll give you some context so we can audit our roadmap. The people in the room are sign interpreters. The input stream they receive has subtitles which they must have access to. While the session is running, they need to see the input stream in a synchronized way as the final output contains the original stream mixed with the video of one of the interpreters, plus the subtitles. The problem with the approach you're suggesting is that each interpreter's HLS client will download the chunks with a slightly different strategy/buffering than the others, making it difficult for them to do the interpretation together! What do you think?

**Comment by dmorn** [comment]
How subtitles reach the final stream is still an open question, what would work best in our case is to embed the subtitles in an RTP stream of packets in a way that AWS Medialive can injest them. Summing up, input stream is audio+video+subtitles provided through an HLS manifest. In the room, intepreters see each other and give their signed interpretation. We mix one of them with the original video and forward the stream keeping subtitles in sync.

**Comment by mat-hek** [comment]
That's an interesting case. Indeed, it's not trivial to make HLS playback perfectly in sync, though I'm not sure if impossible. To answer the initial question
> the first step would be to create a Source implementation that is capable of providing HLS chunks

basically yes. The main things to do would be to:
- Parse HLS manifest
- Download chunks
- Demux the chunks (CMAF demuxer needed)
- Transcode AAC to OPUS (we have the needed elements)
- Integrate with the RTC Engine

If you decide to go for it, we can offer some help and CR if you're interested ;)

**Comment by dmorn** [comment]
Nice! We control the input stream as well and we're emitting H264/AAC mixed in TS chunks! Is https://github.com/membraneframework/membrane_h264_ffmpeg_plugin sufficient for demuxing?

> If you decide to go for it, we can offer some help and CR if you're interested ;)
Well, thank you that would be more than welcome! :D

**Comment by dmorn** [comment]
I see, thanks for the clarification! So as far as I get it the Source itself will provide an output cap with the following properties

- demand_mode: :manual # seems like auto should only be used with filters?
- availability: :on_request # I do not understand the implication of putting :always here!
- mode: :push # we're working with a live playlist that keeps only the latest chunks available. Each time the "manifest tracker" sees a new segment, it downloads and pushes it through the pad. Is it wanted or it is better to use the pull design?
- caps: ? # something that can be linked against the mpegts plugin or a future CMAF demuxer?

I think the behaviour of the Source should change based on the Manifest type: if it is a VOD it should emit the chunks from the beginning, if it is an EVENT it should follow the latest ones! What do you think @mat-hek ?

**Comment by mat-hek** [comment]
> I think the behaviour of the Source should change based on the Manifest type: if it is a VOD it should emit the chunks from the beginning, if it is an EVENT it should follow the latest ones! 

I think so, in case of live playlists there should also be some kind of buffer, as the source will act a bit like a player. I suppose starting with VOD only may be a good approach.

> So as far as I get it the Source itself will provide an output cap with the following properties
demand_mode: :manual # seems like auto should only be used with filters?
availability: :on_request # I do not understand the implication of putting :always here!
mode: :push # we're working with a live playlist that keeps only the latest chunks available. Each time the "manifest tracker" sees a new segment, it downloads and pushes it through the pad. Is it wanted or it is better to use the pull design?
caps: ? # something that can be linked against the mpegts plugin or a future CMAF demuxer?

Please go through the tutorials here: https://membrane.stream/learn, they should hopefully clarify that. If you still have questions regarding Membrane itself, let's talk on our discord https://discord.com/invite/nwnfVSY

**Comment by dmorn** [comment]
Perfect! We're a bit in a rush so we'll have to implement EVENT first even though it is not optimal.

**Comment by mat-hek** [comment]
Sure, I thought you need both. But if you're in rush, be warned that it's not going to be a simple task and RTC Engine is still in beta :P
