### ISSUE TITLE
Why SinkBin doesn't accept H264 `main` profile ?

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_http_adaptive_stream_plugin#80]
Creating HLS playlists with H264 `main` profile with the following elements `MP4 H264 payloader -> CMAF -> HLS Sink` works fine on the browser. Why then not allowing this profile on the accepted ones in [`SinkBin`](https://github.com/membraneframework/membrane_http_adaptive_stream_plugin/blob/master/lib/membrane_http_adaptive_stream/sink_bin.ex#L103) ?

**Comment by varsill** [comment]
Hello, indeed it seems to be just an oversight.  We have added the support for profiles with `b-frames` in CMAF some time ago and the restrictions concerning the H.264 profiles in HLS SinkBin are no longer needed. I will take a look and confirm that it's not a causing any problems and then it should be fixed before the next release.
